version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
         key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
         name: install-dependency
         command: npm install
      - save_cache:
         key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
         paths:
           - ./node_modules
      - run:
         name: lint
         command: npm run lint
