version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
         key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
         name: install-dependency
         command: yarn --frozen-lockfile
      - save_cache:
         key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
         paths:
           - ./node_modules
      - run:
         name: lint
         command: yarn lint
